#!/bin/sh
set -e

# log files should be writable by storm user
chown storm:storm /var/log/storm

# storm.local.dir should also be writable by storm user
chown storm:storm /var/lib/storm
chown storm:storm /var/lib/storm/storm-local

#DEBHELPER#

[ "$1" = "configure" ] && ldconfig

exit 0
